### ISSUE TITLE
為什麽沒有驗證集？

### ISSUE THREAD

**Issue by zjuPeco** [licaiwang/AUTO_VC_tensorflow2.0#1]
你好，請教一下。這裏為什麽沒有驗證集呢？有一個驗證集來判斷模型停止訓練的時間不是更好一些嗎？

**Comment by licaiwang** [comment]
有需要的話你可以自己加，但我自己研究不同模型的時候是希望能跟原來版本訓練的 step 數一樣來比較

**Comment by zjuPeco** [comment]
好的，感謝🙏
